#theme: jekyll-theme-midnight
theme: jekyll-theme-hacker
#remote_theme: "dracula/gh-pages"

title: simulacra tools
description: stella cannefax's blog

posts: 
  test-post:
    url: test-post
    title: test post
  unity-webgl-interop-buffers:
    url: unity-webgl-interop-buffers
    title: Unity WebGL Interop - Buffers
