#theme: jekyll-theme-midnight
theme: jekyll-theme-cayman
#remote_theme: "dracula/gh-pages"

title: simulacra tools
description: stella cannefax's blog

posts: 
  test-post:
    url: test-post
    title: test post
